//
//  DataContext.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import AlecrimCoreData
let dataContext = DataContext()
final class DataContext: AlecrimCoreData.Context {

    var messages: AlecrimCoreData.Table<Message> { return AlecrimCoreData.Table<Message>(context: self) }
    var users: AlecrimCoreData.Table<User> { return AlecrimCoreData.Table<User>(context: self) }

}
