source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
platform:ios, "8.0"
use_frameworks!
pod 'Alamofire'
pod 'Kingfisher'
#pod 'AlamofireImage'
pod 'Cartography',:git => 'https://github.com/robb/Cartography.git'
pod 'CryptoSwift'
pod 'SwiftyJSON'
pod 'Starscream',:head
pod 'DynamicColor'
#pod 'GCDKit', :git => 'https://github.com/JohnEstropia/GCDKit.git',:branch => 'beta'
pod 'CoreStore', :git => 'https://github.com/JohnEstropia/CoreStore.git',:branch => 'develop'
#pod 'Qiniu'
pod 'Timepiece', :git => 'https://github.com/naoty/Timepiece.git',:branch => 'swift-2.0'
pod 'Moya', '~> 2.2.2'
pod 'Moya/ReactiveCocoa'
# Include the following only if you want to use ReactiveCocoa extensions with Moya
#pod 'ReactiveCocoa', '3.0-beta.6'
#pod 'Moya/Reactive'
#pod 'APIKit',:git => 'https://github.com/ishkawa/APIKit.git',:branch => 'swift2'
#pod 'ReactiveCocoa', :git => 'https://github.com/ReactiveCocoa/ReactiveCocoa.git',:branch => 'swift2'
#pod 'AlecrimCoreData', :git => 'https://github.com/kingslay/AlecrimCoreData.git'
