source 'https://github.com/CocoaPods/Specs.git'
platform:ios, "8.0"
use_frameworks!
pod 'Kingfisher', :head
pod 'Alamofire', :head
pod 'Cartography', :head
pod 'CryptoSwift', :head
#pod 'ReactiveCocoa', :head
pod 'APIKit', :head
pod 'SwiftyJSON', :head
pod 'ObjectMapper', :head
pod 'Async', :git => 'https://github.com/duemunk/Async.git'
pod 'AlecrimCoreData', :head
pod 'Starscream', :head